global:
  scrape_interval: 15s
  external_labels:
    monitor: "monitor"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["127.0.0.1:9090"]
  - job_name: "node"
    static_configs:
      - targets: ["node_exporter:9100"]
        labels:
          group: "docker-host"
  - job_name: "docker"
    static_configs:
      - targets: ["cadvisor:8080"]
        labels:
          group: "docker-container"
